fortuneList = [
	'Your road to glory will be rocky, but fulfilling.',
	'Patience is your ally at the moment. Don’t worry!',
	'Your efforts will be worthwhile.',
	'You will make many changes before finding excellence.',
	'A dream you have will come true.',
	'Your ability for accomplishment will be followed by success.',
	'We cannot direct the wind but we can adjust the sails.',
	'Your high-minded principles spell success.',
	'Hard work pays off in the future, laziness pays off now.',
	'Change can hurt, but it leads a path to something better.',
	'Endurance and persistence will be rewarded.',
	'You will overcome difficult challenges to achieve your goals.',
	'Keep a positive mind for a vibrant life.',
	'Your life will be filled with magical moments.',
	'Dream big for your dreams are closer than you think.',
	"Don't wait for success, create it.",
	'Rise above the storm to discover the sunshine.',
	'Your greatest fear is the greatest weapon of your enemy.',
	'Good health and happiness will be your greatest treasures.',
	'A thrilling time is in your near future.',
	'Your destiny lies before you. Choose wisely.',
	'The greatest risk is not taking one.',
	'Kindness is a daily choice.',
	'Opportunities multiply as they are seized.',
	'Creativity is intelligence having fun.',
	'Problems are not stop signs, they are guidelines.',
	'You will become great if you believe in yourself.',
	'A dubious friend may be an enemy in camouflage.',
	'A faithful friend is a strong defense.',
	'A fresh start will put you on your way.',
	'A friend asks only for your time not your money.',
	'A golden egg of opportunity falls into your lap this month.',
	'A hunch is creativity trying to tell you something.',
	'A lifetime of happiness lies ahead of you.',
	'You will soon witness an awesomeness.',
	'You will engage in a profitable business activity. Avoid the shady ones.',
	'Your financial outlook is looking up, then down, then up.',
	'You are on a path of self-discovery.',
	'You are admired by many animals - watch out!',
	'You will receive a gift from a deer.',
	'You will travel to many exotic places with dancers.',
	'Your kindness will be repaid (minus interest)',
	'You will find hidden treasures where least expected.',
	'Your talents will be recognized and rewarded.',
	'You will be successful in your career.',
	'You will find peace in nature.',
	'You will receive unexpected support on Tuesday.',
	'You will achieve all your goalies.',
	'Your dreams are worth chasing.',
	'A pleasant surprise is in store for you.',
	'Good luck will be yours.',
	'You will come into a fortune. This one! Hit again.',
	'You will receive some high prize or award.',
	'Your present plans are going to succeed.',
	'You will make a wise choice, but only one. Then more maybe.',
	'You will be recognized and honored as a community leader.',
	'Your ability to juggle will take you far.',
	'A much needed vacation will bring a great deal of enjoyment.',
	'Your difficulties will strengthen you.',
	'Your dreams are never silly; depend on them to guide you.',
	'Your example will inspire others.',
	'You will become better acquainted with a coworker.',
	'You will soon embark on a thrilling adventure.',
	'A new opportunity will present itself to you on Wednesday.',
	'Good luck will follow you wherever you go.',
	'Your creativity will be at its peak on Thursday.',
	'A long-lost friend will reach out to you on the 15th.',
	'Happiness is just around the corner. Go to the corner.',
	'Your hard work will pay off handsomely.',
	'An unexpected windfall is in your future. Bring a umbrella.',
	'New friendships will enrich your life.',
	'A lucky charm will bring you good fortune. Watch out for leprechauns',
	'A major obstacle will soon be overcome.',
	'Your dreams will become a reality with persistence.',
	'You will discover a hidden talent within yourself.',
	'A small gesture of kindness will have a big impact.',
	'Your financial situation will improve 3 months to the day.',
	'An exciting journey awaits you in September.',
	'You will find a solution to a long-standing problem.',
	'Your positive attitude will attract great opportunities.',
	'A wise decision will lead you to success and wontons.',
	'You will make a lasting impression on someone important.',
	'A moment of clarity will guide you towards your goals.',
	'A gift of wontons will come your way.',
	'Your health will flourish with good habits and good wontons.',
	'You will be recognized for your hard work and dedication with wontons.',
	'An exciting change is on the wonton horizon.',
	'The best wonton is yet to come. Stay optimistic.',
	'A mentor will guide you towards greatness and great wontons.',
	'Your determination will inspire others.',
	'A lucky break and some wontons would brighten your day.',
	'The future is looking bright. Embrace wontons.',
	'You will find harmony and wontons in unexpected places.',
	'Let go of the past and embrace new beginnings.',
	'Your intuition will lead you in the right direction for wontons.',
	'Success is within your grasp. Reach for wontons.',
	'A once-in-a-lifetime opportunity will knock on your door. With wontons',
	'Your efforts will be rewarded with wontons.',
	'Believe in yourself, and you will conquer any challenge.',
	'A friendship will blossom into something meaningful.',
	'You will receive wontons for your hard work.',
	'Your unique talents will shine brightly.',
	'An unexpected encounter will lead to a new friendship over wontons.',
	'Let go of negativity to make room for positivity.',
	'Your resourcefulness will lead to great success.',
	'A period of good luck is on the horizon.',
	'You will receive a surprise gift from someone special.',
	'An important decision will lead to a positive change.',
	'Your positive energy will attract wontons.',
	'A life-changing opportunity will present itself soon.',
	'You will overcome a difficult challenge with grace.',
	'A kind gesture will have a ripple effect.',
	'Your wontons are worth pursuing. Go after them.',
	'A new chapter in your life is about to begin.',
	'You will receive a piece of valuable wonton.',
	'A new hobby will bring you joy and fulfillment.',
	'You will achieve a long-term goal sooner than you think.',
	'An unexpected wonton will brighten your day.',
	'Your creativity will lead to new opportunities.',
	'A chance wonton will lead to a meaningful connection.',
	'Your positive outlook will attract good fortune.',
	"A project you've been working on will be successful.",
	'A journey of self-discovery will lead to wontons.',
	'You will receive recognition for your talents.',
	'Your strong willpower will lead to great achievements.',
	'A small act of kindness will make a big impact.',
	'Your dedication will lead to significant progress.',
	'A happy surprise will come from an unexpected source.',
	'Your charisma will draw wontons towards you.',
	'Your determination will lead you to victory.',
	"A wish you've made will soon be granted, with wontons.",
	'Your intuition will guide you towards the right path.',
	'An old problem will be resolved in a new way.',
	'You will be blessed with good health and happiness.',
	'Your generosity will come back to you tenfold.',
	'A period of joy and celebration is coming your way.',
	'A new friendship will bring wontons into your life.',
	"You will be pleasantly surprised by a colleague's support.",
	'Your hard work will lead to well-deserved wontons.',
	'An exciting adventure awaits you in a distant land.',
	'A newfound skill will lead to exciting opportunities.',
	'You will find inspiration in unexpected places.',
	'A cherished wonton will become a reality.',
	'Your perseverance will pay off in the long run.',
	'You will be presented with a life-changing opportunity.',
	'Your positive attitude will attract abundance.',
	'A peaceful resolution will come from open communication.',
	'A lucky break will open new doors for you.',
	'Your determination will overcome any obstacles.',
	'A positive change is on its way to your life.',
	'With great power comes great wontons.',
	'You will find your ninja ways.',
	'You will meet a mysterious film enthusiast.',
	'An awesome indie movie is waiting for you.',
	'New Foods await you in the upcoming Fridays.',
	'Hey! I found you. Come get some tea.',
	'A jumping spider will befriend you.',
	'Pairs of Pears will greet you next summer.',
	'Come get tea at Happy Earth Tea!',
	'A great story will come from great grapes.',
	'Wow! Yak Cheese!',
	'Your hard work will pay off but you have to pay it back with interest.',
	'Fast pony will go fast.',
	"Life's a mountain not a beach, you will climb.",
	"A sync stranger with tea awaits you this week.",
	"You will be rewarded for your hard work, but you need to work hard. Like not only a day but at least an entire season.",
	"Spicy food will reawaken something sleeping in your life.",
	"You will become a powerful water bender.",
	"Six seasons and a movie",
	"Everything will be ok. Maybe not the way you'd expect.",
	"Success will be determined by how well your sleep.",
	"A smile will confuse a frown.",
	"Sometimes moving slower will get you to wontons faster.",
	"You will find focus in deep solitude.",
	"Traveling awaits you."
];
